fastnlp/fastNLP

fastNLP/loader/config_loader.py

add ConfigSection class to save config data

update config loader

---

fastNLP/action/inference.py
fastNLP/action/metrics.py
fastNLP/action/optimizor.py
fastNLP/action/tester.py
fastNLP/action/trainer.py
fastNLP/loader/dataset_loader.py
fastNLP/loader/preprocess.py
fastNLP/modules/aggregation/kmax_pool.py
fastNLP/modules/aggregation/linear_attention.py
fastNLP/modules/aggregation/self_attention.py
fastNLP/modules/encoder/char_embedding.py
fastNLP/modules/encoder/conv.py
fastNLP/modules/encoder/embedding.py
fastNLP/modules/encoder/lstm.py
test/test_loader.py

优化了preprocessor和dataset loader，确保在POS任务上dataset loader返回多级list结构，preprocessor完成构造词典等工作。与ClassDatasetLoader保持一致

add init parameters in modules; optimize Preprocessor; add metrics.py

---

README.md
test/readme_example.py

modify readme example

---

README.md

- pypi version
- license
- documentation status

add more badges in README

---

fastNLP/core/batch.py

Add support for sorted output within a batch, can be useful when using RNN in Pytorch with `pack_padded_sequence` & `pad_packed_sequence`

fix & update batch

---

fastNLP/api/processor.py
fastNLP/core/optimizer.py
fastNLP/core/tester.py
fastNLP/core/trainer.py
fastNLP/core/utils.py
test/api/test_pipeline.py
test/api/test_processor.py
test/core/test_metrics.py
test/core/test_trainer.py
tutorials/fastnlp_1_minute_tutorial.ipynb

对v0.2版本的微小改进
有些用户反馈的意见已经落实好了；旧的测试挂了，需要更新。
-	[X] The PR title starts with [$CATEGORY] (例如[bugfix]修复bug，[new]添加新功能，[test]修改测试，[rm]删除旧代码)
-	[X] Changes are complete (i.e. I finished coding on this PR)  修改完成才提PR
-	[X] All changes have test coverage  修改的部分顺利通过测试。对于fastnlp/fastnlp/*的修改，测试代码**必须**提供在fastnlp/test/*。
-	[X] Code is well-documented  注释写好，API文档会从注释中抽取
-	[X] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change  修改导致例子或tutorial有变化，请找核心开发人员
- optimzer中调整默认参数大小  …
- 移动Tester中device获取位置
- trainer中
- train()返回一个dict，并重新加载最佳模型
- check_code时返回batch_x中每个数据的形状等信息
- 添加 更多教程内容 …

[test]Updates

---

fastNLP/core/losses.py
fastNLP/core/metrics.py
fastNLP/core/trainer.py
fastNLP/core/utils.py

Changes
1.解决trainer加载模型的问题; 
2.删除loss与metric中对*arg的报错

[core] improve trainer, loss and metrics

---

fastNLP/core/dataset.py
fastNLP/io/embed_loader.py
fastNLP/models/biaffine_parser.py
test/models/test_biaffine_parser.py

- 修改了BiaffineParser，更新到最新的接口，并添加了测试
- 优化了embed_loader的执行速度

update parser, optimize embed_loader

---

.travis.yml
fastNLP/core/batch.py
fastNLP/io/base_loader.py
fastNLP/io/config_io.py
fastNLP/io/dataset_loader.py
fastNLP/io/embed_loader.py
fastNLP/io/logger.py
fastNLP/io/model_io.py
fastNLP/modules/aggregator/attention.py
fastNLP/modules/aggregator/self_attention.py
fastNLP/modules/decoder/CRF.py
fastNLP/modules/decoder/MLP.py
fastNLP/modules/dropout.py
fastNLP/modules/encoder/char_embedding.py
fastNLP/modules/encoder/conv.py
fastNLP/modules/encoder/conv_maxpool.py
fastNLP/modules/encoder/embedding.py
fastNLP/modules/encoder/linear.py
fastNLP/modules/encoder/lstm.py
fastNLP/modules/encoder/masked_rnn.py
fastNLP/modules/encoder/transformer.py
fastNLP/modules/encoder/variational_rnn.py
fastNLP/modules/other_modules.py
fastNLP/modules/utils.py

Description：继续改进文档，完善modules/部分
-	[ X ] The PR title starts with [$CATEGORY] (例如[bugfix]修复bug，[new]添加新功能，[test]修改测试，[rm]删除旧代码)
-	[ X ] Changes are complete (i.e. I finished coding on this PR)  修改完成才提PR
-	[ X ] All changes have test coverage  修改的部分顺利通过测试。对于fastnlp/fastnlp/*的修改，测试代码**必须**提供在fastnlp/test/*。
-	[ X ] Code is well-documented  注释写好，API文档会从注释中抽取
-	[ X ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change  修改导致例子或tutorial有变化，请找核心开发人员
- **改进modules/部分的注释，增加文档可读性**
- **由于CI的环境有变化，对CI配置做了适应性修改**

[Doc] Improve Documentation (2)

---

fastNLP/models/enas_controller.py
fastNLP/models/enas_model.py
fastNLP/models/enas_trainer.py
fastNLP/models/enas_utils.py
test/models/test_enas.py

Description: Add a new model ENAS, the implementation of the paper _Efficient Neural Architecture Search via Parameters Sharing_. In this paper, the authors propose an efficient method to automatically search RNN Cells.
I add 4 files in fastnlp/models, because I believe it would be better not letting the ENAS-specific functions interfere with the core files. It includes a fastnlp-style model of RNN (for which the structure is what the ENAS is searching), and a controller, a trainer (for many reasons I could not use the fastnlp.core.trainer to implement ENAS) and some utilities.
Main reason: Add NAS.
-	[x] Changes are …

[new] Add ENAS (Efficient Neural Architecture Search)

---

fastNLP/modules/encoder/star_transformer.py
fastNLP/modules/encoder/transformer.py
test/modules/test_other_modules.py

- 添加了新的encoder。用于序列标注和文本分类等任务的 Star-Transformer（paper: https://arxiv.org/abs/1902.09113）
@修改过这个文件的人
@核心开发人员

Add Star-Transformer

---

fastNLP/modules/encoder/star_transformer.py

fix the bug described in #138 . Thank @wlhgtc for bug reporting and pr.

fix mask bug in star-transformer

---

fastNLP/modules/encoder/star_transformer.py

Another bug in Star Transformer

---

fastNLP/modules/encoder/variational_rnn.py

fix for changing torch API

---

fastNLP/io/data_loader/sst.py
fastNLP/models/star_transformer.py
fastNLP/modules/encoder/star_transformer.py
reproduction/Star_transformer/datasets.py
reproduction/Star_transformer/run.sh
reproduction/Star_transformer/train.py

Description：对Star-Transformer实现做了简略的修改，提升在SST数据集上的性能（运行run.sh应可以得到51.2的结果），后续会继续完善，具体修改内容如下
- 修改测试逻辑
- 修改随机种子设定（现在每次运行同一种子依旧会得到略有不同的结果，可能是精度或fastNLP内部问题，待查）
- 修改了词表建立过程
- 修改了数据读取过程
- 修改了传参过程（原有的部分超参设定无效，比如 classifier的dropout）
- 修改了weight_decay的适用范围
- 修改了glove中missing word 的初始化逻辑
- 不同参数类型有了不同的初始化
- 加入了spacy tokenizer
- 改用了bucket sampler
- 暂时禁用了 position embedding
- 暂时禁用了 embedding fc
- 暂时禁用了 learning rate 的 warm up
超参做了一定的简化，目前运行速度还存在一定问题，待优化。
Main reason: #148 
@xpqiu @choosewhatulike

[bugfix] hot fix for Star-Transformer on SST

---

reproduction/coreference_resolution/data_load/cr_loader.py
reproduction/coreference_resolution/model/config.py
reproduction/coreference_resolution/model/metric.py
reproduction/coreference_resolution/model/model_re.py
reproduction/coreference_resolution/model/preprocess.py
reproduction/coreference_resolution/model/softmax_loss.py
reproduction/coreference_resolution/model/util.py
reproduction/coreference_resolution/readme.md
reproduction/coreference_resolution/test/test_dataloader.py
reproduction/coreference_resolution/train.py
reproduction/coreference_resolution/valid.py

Description：增加了指代消解论文复现的源代码。
Main reason: 增加复现模块。
-	[ ✅] The PR title starts with [$CATEGORY] (例如[bugfix]修复bug，[new]添加新功能，[test]修改测试，[rm]删除旧代码)
-	[ ✅] Changes are complete (i.e. I finished coding on this PR)  修改完成才提PR
-	[✅] Code is well-documented  注释写好，API文档会从注释中抽取
- 增加指代消解源码

[new]增加指代消解源码

---

reproduction/matching/matching_cntn.py
reproduction/matching/model/cntn.py

Description：增加了CNTN模型
@修改过这个文件的人 …

Add cntn model for matching.

---

reproduction/text_classification/data/IMDBLoader.py
reproduction/text_classification/data/sstLoader.py
reproduction/text_classification/data/yelpLoader.py

[bugfix] IMDB/SST/YELP dataloader char_level无空格 [add]IMDB/SST use spacy tokenizer 

---

reproduction/Summmarization/BertSum/callback.py
reproduction/Summmarization/BertSum/dataloader.py
reproduction/Summmarization/BertSum/metrics.py
reproduction/Summmarization/BertSum/model.py
reproduction/Summmarization/BertSum/train_BertSum.py
reproduction/Summmarization/BertSum/utils.py

[add] BertSum model (Liu et al. 2019)

---

docs/source/tutorials/batch,loss,optimizer教程-以文本分类为例.rst

改成使用SST数据集的batch,loss,optimizer教程

---

fastNLP/io/data_loader/sst.py
fastNLP/models/star_transformer.py
fastNLP/modules/encoder/star_transformer.py
reproduction/Star_transformer/README.md
reproduction/Star_transformer/train.py
reproduction/seqence_labelling/ner/model/dilated_cnn.py
reproduction/seqence_labelling/ner/train_idcnn.py
reproduction/text_classification/train_dpcnn.py

[bug fix] fix test case for sstloader & update some train scripts

---

fastNLP/io/data_loader/matching.py
reproduction/matching/matching_mwan.py
reproduction/matching/model/mwan.py

Description：添加了mwan模型的实现以及训练代码，另外给mathing dataloader添加了一个option
- 添加了新模型；用于matching，来自 Chuanqi Tan et.al. 的 《Multiway Attention Networks for Modeling Sentence Pairs》
- 修改 io.data_loader.matching.MatchingLoader …

[new] add mwan model

---

fastNLP/io/file_utils.py
fastNLP/io/loader/classification.py
fastNLP/io/loader/matching.py

补充了两个数据集的download

---

fastNLP/io/loader/matching.py

修改了CNXNLI的_load()，可以处理特殊的instance格式如下：

---

fastNLP/io/pipe/matching.py

添加了中文pipe的初始化使用按字tokenize

---

reproduction/seqence_labelling/chinese_ner/LatticeLSTM/check_output.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/load_data.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/main.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/models.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/modules.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/pathes.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/small.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/utils.py
reproduction/seqence_labelling/chinese_ner/LatticeLSTM/utils_.py

Description：实现支持batch并行的lattice lstm
Main reason: 实现支持batch并行的lattice lstm
-	[x] The PR title starts with [new] (例如[bugfix]修复bug，[new]添加新功能，[test]修改测试，[rm]删除旧代码)
-	[ ] Code is well-documented  注释写好，API文档会从注释中抽取，只写了模型的部分
- 添加了新模型；实现了Jie Yang的Chinese NER Using Lattice LSTM，能够在weibo和resume数据集上明显超过原文报告的性能，在ontonote上差原文报告性能0.3个点
@yhcc 
@xpqiu …

batch-support LatticeLSTM

---

reproduction/text_classification/README.md
reproduction/text_classification/train_char_cnn.py

[verify] char_cnn使用pipe，移除dataloader以及环境变量相关代码

---

reproduction/multi-criteria-cws/README.md
reproduction/multi-criteria-cws/data-prepare.py
reproduction/multi-criteria-cws/data-process.py
reproduction/multi-criteria-cws/main.py
reproduction/multi-criteria-cws/make_data.sh
reproduction/multi-criteria-cws/models.py
reproduction/multi-criteria-cws/optm.py
reproduction/multi-criteria-cws/train.py
reproduction/multi-criteria-cws/train.sh
reproduction/multi-criteria-cws/transformer.py
reproduction/multi-criteria-cws/utils.py

添加了新论文的复现《 Multi-Criteria Chinese Word Segmentation with Transformer 》，详情请查看  reproduction/multi-criteria-cws 里面的 README。

[add] reproduction of multi-criteria cws

---

fastNLP/core/dataset.py
fastNLP/core/metrics.py
fastNLP/io/file_utils.py
fastNLP/io/loader/classification.py
fastNLP/models/cnn_text_classification.py
fastNLP/models/snli.py
test/core/test_metrics.py

- 修改了两个bug
- 对部分文档内容进行了更新
- 增加了分类问题的f值计算metric
@修改过这个文件的人
@核心开发人员

[update]小幅度更新

---

fastNLP/core/losses.py
fastNLP/core/metrics.py
fastNLP/embeddings/bert_embedding.py
fastNLP/embeddings/char_embedding.py
fastNLP/models/biaffine_parser.py
fastNLP/models/snli.py
fastNLP/modules/decoder/crf.py
fastNLP/modules/decoder/utils.py
fastNLP/modules/encoder/star_transformer.py
fastNLP/modules/encoder/transformer.py
reproduction/Summarization/Baseline/model/Loss.py
reproduction/Summarization/Baseline/model/Metric.py
reproduction/Summarization/BertSum/model.py
reproduction/joint_cws_parse/models/CharParser.py
reproduction/matching/model/esim.py
reproduction/matching/model/mwan.py
reproduction/multi-criteria-cws/transformer.py

修复针对pytorch1.3.0版本bug的一个bug

---

fastNLP/io/file_reader.py

出现非法格式catch住的时候，应该将sample清空，不然会一直报warning，sample也会一直累积新的内容得不到正确的更新。
- …

出现非法格式catch住的时候，应该将sample清空

---

fastNLP/core/metrics.py
fastNLP/core/utils.py
test/core/test_metrics.py

Description：增加了ConfusionMatrixMetric与ConfusionMatrix类
Main reason:  补充分类混淆矩阵类到utils
- 添加了混淆矩阵类
@修改过这个文件的人
@核心开发人员

[new] add ConfusionMatrix, ConfusionMatrixMetric

---

fastNLP/core/metrics.py
fastNLP/core/utils.py

Description：代码解构，增加数据提取方法，格式化输出方法，增加元素占比计算方法
Main reason: 功能完善，代码结构调整
Checklist 检查下面各项是否完成
- 添加了新方法；增加数据提取方法，格式化输出方法，增加元素占比计算方法
- 代码结构调整
@修改过这个文件的人
@核心开发人员

[new]revised confusion class

---

fastNLP/core/metrics.py
test/core/test_metrics.py

Description：固定f1 metric 的test数据
Main reason: 旧版本报错
- 固定f1 metric 的test数据
@修改过这个文件的人
@核心开发人员

[test] fix f1 test

---

fastNLP/embeddings/bert_embedding.py

Description：修改token_type_ids编号反转方法
Main reason: 原本的方法对于多个句子sep个数不同的情况会有问题
- 修改token_type_ids编号反转方法
@修改过这个文件的人
@核心开发人员

[bugfix] token_type_id_rev

---

fastNLP/core/callbacks/load_best_model_callback.py

Description：LoadBestModelCallback中，训练后加载最佳模型时的 log提示，加入该模型是在哪个 epoch，batch 产生的。
Main reason: LoadBestModelCallback中，训练后加载最佳模型时的 log提示，加入该模型是在哪个 epoch，batch 产生的。
- LoadBestModelCallback 增加成员变量 `self.meta`，用于储存生成最佳模型时的 …

[bugfix] LoadBestModelCallback log增加有用信息

---

fastNLP/transformers/torch/models/__init__.py
fastNLP/transformers/torch/models/auto/configuration_auto.py
fastNLP/transformers/torch/models/auto/modeling_auto.py
fastNLP/transformers/torch/models/auto/tokenization_auto.py
fastNLP/transformers/torch/models/elasticbert/__init__.py
fastNLP/transformers/torch/models/elasticbert/configuration_elasticbert.py
fastNLP/transformers/torch/models/elasticbert/modeling_elasticbert.py

Description：在transformers文件夹添加elasticbert模型
Main reason: 添加elasticbert模型
- 添加了新模型; 一个多出口的预训练语言模型ElasticBERT，来自刘向阳的Towards Efficient NLP: A Standard Evaluation and A Strong Baseline
@修改过这个文件的人 …

[new] add elasticbert
